
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace host.ui {
    using Terminal.Gui;
    
    
    public partial class LoginDialog {
        
        public string User { get; private set; }
        public string Password { get; private  set; }

        public LoginDialog(string user = "", string pass = "", string error = ""){
            User = user;
            Password = pass;
            InitializeComponent();
            lblError.Text = error;
            txtUser.Text = this.User;
            txtPass.Text = this.Password;
            txtUser.TextChanged += (a)=>{lblError.Text = "";};
            txtPass.TextChanged += (a)=>{lblError.Text = "";};
            btnOk.Clicked += ()=>{
                User = txtUser.Text.ToString(); 
                Password = txtPass.Text.ToString();
                this.RequestStop();
                
            };  
        }

        
    }
}
